const fs = require("fs");
const path = require("path");

const {
  createHuaweiDeck,
  repairPptxForPowerPointCom,
  safeText,
  textBox,
} = require("../hw_pptx_helpers");
const { measureWithPowerPoint } = require("../measure_pptx_layout");
const {
  createVisualAnchorImage,
  renderVisualAnchorPptNative,
  resolveRoughSvgSizeTierForArea,
  resolveVisualAnchorRenderPath,
} = require("../hw_diagram_helpers");

const ROOT = path.resolve(__dirname, "..", "..", "..");
const PT_PER_IN = 72;

function usage() {
  console.error("Usage: node scripts/pptx/layout/powerpoint_measurement_worker.js <request.json> <output.json>");
}

function marker(slide, id) {
  textBox(slide, `MEASURE_ID:${id}`,
    {
    x: 0.05,
    y: 0.05,
    w: 1.2,
    h: 0.14,
    fontSize: 8,
    color: "FFFFFF",
    margin: 0,
  });
}

async function main() {
  const timings = [];
  const start = Date.now();
  const mark = (label) => timings.push({ label, ms: Date.now() - start });
  const requestPath = process.argv[2];
  const outputPath = process.argv[3];
  if (!requestPath || !outputPath) {
    usage();
    process.exit(2);
  }
  const payload = JSON.parse(fs.readFileSync(requestPath, "utf8"));
  const batchRequests = Array.isArray(payload?.requests) ? payload.requests : null;
  const request = batchRequests ? null : payload;
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  const workDir = path.join(ROOT, ".tmp", "powerpoint_layout_measurement_probe");
  fs.mkdirSync(workDir, { recursive: true });
  const stem = path.basename(outputPath, ".json");
  const pptxPath = path.join(workDir, `${stem}.pptx`);
  const manifestPath = path.join(workDir, `${stem}.measurement.json`);

  try {
    await buildProbeDeck(batchRequests || [{ id: "probe", request }], pptxPath);
    mark("build_probe_deck");
    await repairPptxForPowerPointCom(pptxPath);
    mark("repair_pptx");
    await runMeasurement(pptxPath, manifestPath);
    mark("powerpoint_measure");
    const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
    const result = batchRequests
      ? batchMeasurementResult(batchRequests, manifest)
      : measurementResult(request, manifest, "probe");
    if (process.env.HW_MEASUREMENT_PROFILE === "1") {
      result.profile = {
        total_ms: Date.now() - start,
        timings,
      };
    }
    fs.writeFileSync(outputPath, JSON.stringify(result, null, 2), "utf8");
  } catch (error) {
    fs.writeFileSync(outputPath, JSON.stringify({
      ok: false,
      error: String(error.stack || error.message || error),
      request,
    }, null, 2), "utf8");
    process.exit(0);
  }
}

async function buildProbeDeck(request, pptxPath) {
  const pptx = createHuaweiDeck({
    title: "PowerPoint layout measurement probe",
    subject: "Temporary probe deck generated by layout measurement worker",
  });
  const entries = Array.isArray(request) ? request : [{ id: "probe", request }];
  entries.forEach((entry, index) => {
    const slide = pptx.addSlide();
    slide.background = { color: "FFFFFF" };
    const id = entry.id || `probe_${index + 1}`;
    const item = entry.request || entry;
    marker(slide, `${id}\nMEASURE_KIND:${item.kind || "unknown"}`);
    const block = item.block || {};
    const visualAnchor = block.visual_anchor || block.visualAnchor;
    const area = probeArea(item);
    if (visualAnchor) {
      renderProbeVisualAnchor(slide, normalizeVisualAnchor(visualAnchor), area);
    } else {
      textBox(slide, normalizeTextBody(block), {
        ...area,
        fontSize: Number(block.fontSize || block.contentFontSize || 12),
        bold: Boolean(block.bold ?? true),
        color: "333333",
        margin: 0.08,
        lineSpacingMultiple: Number(block.lineSpacingMultiple || 1.5),
      });
    }
  });
  await pptx.writeFile({ fileName: pptxPath });
}

function renderProbeVisualAnchor(slide, visualAnchor, area) {
  const renderPath = resolveVisualAnchorRenderPath(visualAnchor);
  if (renderPath === "rough_svg") {
    const sizeTier = resolveRoughSvgSizeTierForArea(area);
    const widthByTier = { large: 1400, medium: 1100, small: 860 };
    const image = createVisualAnchorImage(visualAnchor, { width: widthByTier[sizeTier] || 1400, sizeTier });
    const imageArea = fitAreaContain(area, image.width, image.height);
    slide.addImage({
      data: `data:${image.mimeType};base64,${Buffer.from(image.svg, "utf8").toString("base64")}`,
      x: imageArea.x,
      y: imageArea.y,
      w: imageArea.w,
      h: imageArea.h,
    });
    return;
  }
  renderVisualAnchorPptNative(slide, visualAnchor, area);
}

function fitAreaContain(area, imageWidth, imageHeight) {
  if (!Number.isFinite(imageWidth) || !Number.isFinite(imageHeight) || imageWidth <= 0 || imageHeight <= 0) {
    throw new Error("fitAreaContain requires positive image dimensions.");
  }
  const areaRatio = area.w / area.h;
  const imageRatio = imageWidth / imageHeight;
  if (imageRatio >= areaRatio) {
    const h = area.w / imageRatio;
    return { x: area.x, y: area.y, w: area.w, h };
  }
  const w = area.h * imageRatio;
  return { x: area.x + (area.w - w) / 2, y: area.y, w, h: area.h };
}

function normalizeVisualAnchor(visualAnchor = {}) {
  return {
    title: `${visualAnchor.kind || "Visual"} ${visualAnchor.template || "component"}`,
    claim: "PowerPoint layout measurement probe.",
    ...visualAnchor,
    id: visualAnchor.id || "measurement_probe_visual",
  };
}

function probeArea(request) {
  const width = Math.max(0.2, Number(request?.area?.w || 1));
  const kind = request.kind;
  const h = kind === "text" ? 5 : kind === "kpi" ? 3.2 : kind === "table" ? 3.2 : 3.2;
  return { x: 1, y: 1, w: width, h };
}

async function runMeasurement(pptxPath, manifestPath) {
  const manifest = await measureWithPowerPoint(pptxPath);
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), "utf8");
}

function batchMeasurementResult(entries, manifest) {
  const results = {};
  entries.forEach((entry, index) => {
    const id = entry.id || `probe_${index + 1}`;
    results[id] = measurementResult(entry.request || entry, manifest, id);
  });
  return { ok: true, kind: "batch", results };
}

function measurementResult(request, manifest, measurementId = "probe") {
  const slide = (manifest.slides || []).find((entry) => entry.measurement_id === measurementId);
  if (!slide) throw new Error(`PowerPoint measurement probe did not return slide ${measurementId}.`);
  const shapes = targetShapes(slide);
  if (request.kind === "text") {
    const textShape = shapes.find((shape) => shape.has_text && !isMarkerShape(shape));
    if (!textShape || !Number(textShape.bound_height)) throw new Error("Text probe did not return TextRange2 bounds.");
    return {
      ok: true,
      kind: request.kind,
      text_bounds: {
        x: round(Number(textShape.bound_left || 0) / PT_PER_IN),
        y: round(Number(textShape.bound_top || 0) / PT_PER_IN),
        w: round(Number(textShape.bound_width || 0) / PT_PER_IN),
        h: round(Number(textShape.bound_height || 0) / PT_PER_IN),
      },
      shape_bounds: boundsToInches(unionBounds([textShape])),
      shape_count: 1,
    };
  }
  const bounds = unionBounds(shapes);
  return {
    ok: true,
    kind: request.kind,
    shape_bounds: boundsToInches(bounds),
    shape_count: shapes.length,
  };
}

function normalizeTextBody(block = {}) {
  const body = block.body || block.items || block.text || "";
  return Array.isArray(body) ? body.map((line) => `- ${safeText(line)}`).join("\n") : safeText(body);
}

function isMarkerShape(shape) {
  return String(shape.text || "").includes("MEASURE_ID:");
}

function targetShapes(slide) {
  return (slide.shapes || []).filter((shape) => !isMarkerShape(shape));
}

function unionBounds(shapes) {
  const realShapes = shapes.filter((shape) => Number(shape.width) > 0 && Number(shape.height) > 0);
  if (!realShapes.length) throw new Error("No measurable shapes returned by PowerPoint.");
  const left = Math.min(...realShapes.map((shape) => shape.left));
  const top = Math.min(...realShapes.map((shape) => shape.top));
  const right = Math.max(...realShapes.map((shape) => shape.left + shape.width));
  const bottom = Math.max(...realShapes.map((shape) => shape.top + shape.height));
  return { left, top, right, bottom, width: right - left, height: bottom - top };
}

function boundsToInches(bounds) {
  return {
    x: round(bounds.left / PT_PER_IN),
    y: round(bounds.top / PT_PER_IN),
    w: round(bounds.width / PT_PER_IN),
    h: round(bounds.height / PT_PER_IN),
  };
}

function round(value) {
  return Number(Number(value || 0).toFixed(3));
}

main().catch((error) => {
  console.error(error.stack || error.message || error);
  process.exit(1);
});
